"""add_quiz_answer_field

Revision ID: 275b289f174b
Revises: 8df4ce4bda52
Create Date: 2025-05-10 12:24:00.174591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275b289f174b'
down_revision: Union[str, None] = '8df4ce4bda52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegramusers', sa.Column('quiz_answer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegramusers', 'quiz_answer')
    # ### end Alembic commands ###
