"""remove_quiz_answer_field

Revision ID: 688c544eac08
Revises: e6c28cad9bc4
Create Date: 2025-05-11 20:39:10.295110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688c544eac08'
down_revision: Union[str, None] = 'e6c28cad9bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegramusers', 'quiz_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegramusers', sa.Column('quiz_answer', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
