"""initial

Revision ID: e6c28cad9bc4
Revises: 
Create Date: 2025-05-11 14:44:28.060489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c28cad9bc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegramusers',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('quiz_answer', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegramusers'))
    )
    op.create_index(op.f('ix_telegramusers_id'), 'telegramusers', ['id'], unique=False)
    op.create_index(op.f('ix_telegramusers_telegram_id'), 'telegramusers', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_telegramusers_username'), 'telegramusers', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegramusers_username'), table_name='telegramusers')
    op.drop_index(op.f('ix_telegramusers_telegram_id'), table_name='telegramusers')
    op.drop_index(op.f('ix_telegramusers_id'), table_name='telegramusers')
    op.drop_table('telegramusers')
    # ### end Alembic commands ###
