"""add_quiz_answer_field

Revision ID: f6c0d68cef47
Revises: 688c544eac08
Create Date: 2025-05-11 21:50:22.517357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c0d68cef47'
down_revision: Union[str, None] = '688c544eac08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegramusers', sa.Column('quiz_answer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegramusers', 'quiz_answer')
    # ### end Alembic commands ###
